explore_node:
  ros__parameters:
    use_sim_time: true
    robot_base_frame: base_footprint
    costmap_topic: map
    visualize: true
    min_frontier_size: 0.335
    planner_frequency: 0.15
    progress_timeout: 30.0
    potential_scale: 1.0
    gain_scale: 3.0